### ISSUE TITLE
Deployement issue

### ISSUE THREAD

**Issue by hrshtmlng** [swarnavopramanik/Admin-Panel#12]
![Web capture_21-5-2023_12592_code-clause-admin-panel vercel app](https://github.com/swarnavopramanik/Admin-Panel/assets/101478591/debe3c0c-d77d-412f-9ca6-230759052327)
This project is having issue that it is not maintained over along period of time so please take a look and redeploye it

**Comment by swarnavopramanik** [comment]
Sorry brother this app I will faild so many time to deploy it because I some issues occur and also one contributor face same problem

If you look into what is app and work get star porject and clone and run your local machine it will work or refer vedio I will atacht in readme file .

If you deploy my successfully it could be beneficial for me ..you try onese please 🙂

**Comment by abhijeetnishal** [comment]
@swarnavopramanik  Hey i will try to redeploy this can you assign me this under GSSOC 2023

**Comment by swarnavopramanik** [comment]
> @swarnavopramanik  Hey i will try to redeploy this can you assign me this under GSSOC 2023

Yeah sure you try please

**Comment by PARTH-1712** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.
